package demo.entities;
// Generated Oct 29, 2017 9:19:33 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "Account", catalog = "mydemo")
public class Account implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private String fullName;
	private String email;
	private String website;
	private String birthDay;
	private Boolean status;
	private String explre;
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Account() {
	}

	public Account(int id, String username) {
		this.id = id;
		this.username = username;
	}

	public Account(int id, String username, String password, String fullName, String email, String website,
			String birthDay, Boolean status, String explre, Set<Role> roles, Set<Orders> orderses) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.email = email;
		this.website = website;
		this.birthDay = birthDay;
		this.status = status;
		this.explre = explre;
		this.roles = roles;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fullName", length = 50)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "email", length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "website", length = 250)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "birthDay", length = 10)
	public String getBirthDay() {
		return this.birthDay;
	}

	public void setBirthDay(String birthDay) {
		this.birthDay = birthDay;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "explre", length = 10)
	public String getExplre() {
		return this.explre;
	}

	public void setExplre(String explre) {
		this.explre = explre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Account_Role", catalog = "mydemo", joinColumns = {
			@JoinColumn(name = "AccountId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "RoleId", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
